BookStore/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreDataAccess.Repository.IRepository;
using BookStoreModels;
using BookStoreUtility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Category category = new Category();

            if (id == null)
            {
                return View(category);
            }

            category = await this._categoryRepository.GetCategory(id.GetValueOrDefault());

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Id == 0)
                {
                    _categoryRepository.Add<Category>(category);
                }
                else
                {
                    _categoryRepository.Update<Category>(category);
                }

                await _categoryRepository.SaveAll();
                return RedirectToAction(nameof(Index));
            }

            return View(category);
        }

        /*
         * ------------------------------------------------------------------------------
         * API INTERNA DE LA APLICACION
         * ------------------------------------------------------------------------------
         */
        [HttpGet("/Admin/Category/datatable")]
        public async Task<IActionResult> GetAll()
        {
            var categories = await _categoryRepository.GetCategories();

            return Ok(categories);
        }

        // DELETE api/categories/id
        [HttpDelete("/Admin/Category/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var category = await _categoryRepository.GetCategory(id);

            if (category == null)
            {
                throw new Exception("Username with ID does not exists");
            }

            _categoryRepository.Delete<Category>(category);
            await _categoryRepository.SaveAll();
            return NoContent();
        }
    }
}

BookStore/Areas/Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreDataAccess.Repository.IRepository;
using BookStoreDataAccess.Repository.Page;
using BookStoreModels;
using BookStoreModels.DTO;
using BookStoreUtility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class CompanyController : Controller
    {
        private readonly ICompanyRepository _companyRepository;

        public CompanyController(ICompanyRepository companyRepository)
        {
            _companyRepository = companyRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Company company = new Company();

            if (id == null)
            {
                return View(company);
            }

            company = await this._companyRepository.GetCompany(id.GetValueOrDefault());

            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(Company company)
        {
            if (ModelState.IsValid)
            {
                if (company.Id == 0)
                {
                    _companyRepository.Add<Company>(company);
                }
                else
                {
                    _companyRepository.Update<Company>(company);
                }

                await _companyRepository.SaveAll();
                return RedirectToAction(nameof(Index));
            }

            return View(company);
        }


        /*
         * ------------------------------------------------------------------------------
         * API INTERNA DE LA APLICACION
         * ------------------------------------------------------------------------------
         */

        // GET Admin/Company/datatable
        [HttpGet("/Admin/Company/datatable")]
        public async Task<IActionResult> GetCompaniesDatatable([FromQuery]DatatableForSelectDTO datatableForSelectDTO)
        {
            // Convert to UserPageParams the API knows
            var userPageParams = new UserPageParams();
            userPageParams.PageNumber = (int)Math.Ceiling(datatableForSelectDTO.Start / (double)datatableForSelectDTO.Length) + 1;
            userPageParams.PageSize = datatableForSelectDTO.Length;


            // Get Data
            var companies = await _companyRepository.GetCompanies(userPageParams);

            // Wrap result in a format Datatable Knows
            var result = new DatatableResponseDTO();
            result.aaData = companies;
            result.draw = datatableForSelectDTO.Draw;
            result.iTotalDisplayRecords = companies.TotalCount;
            result.iTotalRecords = companies.TotalCount;

            Response.AddPagination(companies.CurrentPage, companies.PageSize, companies.TotalCount, companies.TotalPages);
            return Ok(result);
        }

        [HttpDelete("/Admin/Company/{id}")]
        public async Task<IActionResult> DeleteCompany(int id)
        {
            /*
             * ---------------------------------------------------------------------------
             * ZONA DE VALIDACION
             * ---------------------------------------------------------------------------
             */
            // Chequear si el producto existe
            var companyDB = await _companyRepository.GetCompany(id);

            if (companyDB == null)
            {
                throw new Exception($"Company with id {id} does not exist");
            }


            /*
             * --------------------------------------------------------------------------
             * ZONA DE PROCESAMIENTO DE LA PETICION
             * --------------------------------------------------------------------------
             */
            _companyRepository.Delete<Company>(companyDB);
            await _companyRepository.SaveAll();
            return NoContent();
        }
    }
}

BookStore/Areas/Admin/Controllers/CoverTypeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreDataAccess.Repository.IRepository;
using BookStoreModels;
using BookStoreUtility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class CoverTypeController : Controller
    {
        private readonly ICoverTypeRepository _coverTypeRepository;

        public CoverTypeController(ICoverTypeRepository coverTypeRepository)
        {
            _coverTypeRepository = coverTypeRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            CoverType coverType = new CoverType();

            if (id == null)
            {
                return View(coverType);
            }

            coverType = await this._coverTypeRepository.GetCoverType(id.GetValueOrDefault());

            if (coverType == null)
            {
                return NotFound();
            }

            return View(coverType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(CoverType cover)
        {
            if (ModelState.IsValid)
            {
                if (cover.Id == 0)
                {
                    _coverTypeRepository.Add<CoverType>(cover);
                }
                else
                {
                    _coverTypeRepository.Update<CoverType>(cover);
                }

                await _coverTypeRepository.SaveAll();
                return RedirectToAction(nameof(Index));
            }

            return View(cover);
        }



        /*
         * ------------------------------------------------------------------------------
         * API INTERNA DE LA APLICACION
         * ------------------------------------------------------------------------------
         */
        // GET api/covertypes
        [HttpGet("/Admin/CoverType/datatable")]
        public async Task<IActionResult> GetAll()
        {
            var covers = await _coverTypeRepository.GetCoverTypes();

            return Ok(covers);
        }

        // DELETE api/covertypes/id
        [HttpDelete("/Admin/CoverType/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            /*
             * ---------------------------------------------------------------------------
             * ZONA DE VALIDACION
             * ---------------------------------------------------------------------------
             */
            // Chequear si el cover existe
            var cover = await _coverTypeRepository.GetCoverType(id);

            if (cover == null)
            {
                throw new Exception($"Cover with id {id} does not exist");
            }

            /*
             * --------------------------------------------------------------------------
             * ZONA DE PROCESAMIENTO DE LA PETICION
             * --------------------------------------------------------------------------
             */
            _coverTypeRepository.Delete<CoverType>(cover);
            await _coverTypeRepository.SaveAll();
            return NoContent();
        }
    }
}

BookStore/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookStoreDataAccess.Repository.IRepository;
using BookStoreDataAccess.Repository.Page;
using BookStoreModels;
using BookStoreModels.DTO;
using BookStoreModels.ViewModels;
using BookStoreUtility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.ROLE_ADMIN)]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ICoverTypeRepository _coverTypeRepository;

        public ProductController(IProductRepository productRepository, 
            ICategoryRepository categoryRepository,
            ICoverTypeRepository coverTypeRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
            _coverTypeRepository = coverTypeRepository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> Upsert(int? id)
        {
            Product product = new Product();

            if (id != null)
            {
                product = await this._productRepository.GetProduct(id.GetValueOrDefault());

                if (product == null)
                {
                    return NotFound();
                }
            }

            // Creating ViewModel for specific page
            ProductViewModel productViewModel = new ProductViewModel();
            productViewModel.Product = product;
            productViewModel.CategoryList = (await _categoryRepository.GetCategories())
                .Select(i => new SelectListItem { 
                    Text = i.Name,
                    Value = i.Id.ToString()
                });
            productViewModel.CoverTypeList = (await _coverTypeRepository.GetCoverTypes())
                .Select(i => new SelectListItem {
                    Text = i.Name,
                    Value = i.Id.ToString()
                });

            return View(productViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ProductViewModel productViewModel)
        {
            if (ModelState.IsValid)
            {
                if (productViewModel.Product.Id == 0)
                {
                    _productRepository.Add<Product>(productViewModel.Product);
                }
                else
                {
                    _productRepository.Update<Product>(productViewModel.Product);
                }

                await _productRepository.SaveAll();
                return RedirectToAction(nameof(Index));
            }

            return View(productViewModel);
        }


        /*
         * ------------------------------------------------------------------------------
         * API INTERNA DE LA APLICACION
         * ------------------------------------------------------------------------------
         */

        // GET api/products/datatable
        [HttpGet("/Admin/Product/datatable")]
        public async Task<IActionResult> GetProductsDatatable([FromQuery]DatatableForSelectDTO datatableForSelectDTO)
        {
            // Convert to UserPageParams the API knows
            var userPageParams = new UserPageParams();
            userPageParams.PageNumber = (int)Math.Ceiling(datatableForSelectDTO.Start / (double)datatableForSelectDTO.Length) + 1;
            userPageParams.PageSize = datatableForSelectDTO.Length;


            // Get Data
            var products = await _productRepository.GetProduts(userPageParams);

            // Wrap result in a format Datatable Knows
            var result = new DatatableResponseDTO();
            result.aaData = products;
            result.draw = datatableForSelectDTO.Draw;
            result.iTotalDisplayRecords = products.TotalCount;
            result.iTotalRecords = products.TotalCount;

            Response.AddPagination(products.CurrentPage, products.PageSize, products.TotalCount, products.TotalPages);
            return Ok(result);
        }

        // DELETE api/products/1
        [HttpDelete("/Admin/Product/{id}")]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            /*
             * ---------------------------------------------------------------------------
             * ZONA DE VALIDACION
             * ---------------------------------------------------------------------------
             */
            // Chequear si el producto existe
            var productDB = await _productRepository.GetProduct(id);

            if (productDB == null)
            {
                throw new Exception($"Product with id {id} does not exist");
            }


            /*
             * --------------------------------------------------------------------------
             * ZONA DE PROCESAMIENTO DE LA PETICION
             * --------------------------------------------------------------------------
             */
            _productRepository.Delete<Product>(productDB);
            await _productRepository.SaveAll();
            return NoContent();
        }
    }
}

BookStore/Views/Shared/_CreateAndBackToListButtons.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Create</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

BookStore/Views/Shared/_EditAndBackToListButtons.cshtml
@model int
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control" asp-route-id="@Model">Update</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
    </div>
</div>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Dropdown link
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a asp-area="Admin" asp-controller="Category" asp-action="Index" class="dropdown-item">Category List</a>
                                <a asp-area="Admin" asp-controller="CoverType" asp-action="Index" class="dropdown-item">Cover Type List</a>
                                <a asp-area="Admin" asp-controller="Product" asp-action="Index" class="dropdown-item">Product List</a>
                                <a asp-area="Admin" asp-controller="Company" asp-action="Index" class="dropdown-item">Company List</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white-50 bg-primary">
        <div class="container">
            &copy; 2020 - BookStore
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>